language: scala # to trigger the build on JVM worker ('language: java' works the same)
env:
  - PLAY_VERSION=2.2.1 # Latest 2.2.x
services:
- mongodb
before_script:
  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
script: play-${PLAY_VERSION}/play test
notifications: