language: scala
scala:
  - 2.11.1
services:
- mongodb
script:
  - "cd $TRAVIS_BUILD_DIR"
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publish-local"
notifications:
  email: false